spring:
  application:
    name: POS
  datasource:
    url: jdbc:mariadb://localhost:3306/Pos
    username: root
    password: Password1@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: 97bb51bb9d064ad6b220954c5d585f14a09d598df64c2c48e1ae24607cd3b0e0
  expiration: 3600000
logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.web.access: DEBUG
        security.web.access.intercept.FilterSecurityInterceptor: DEBUG
        security.web.authentication: DEBUG
        security.web.authentication.www: DEBUG
        security.oauth2: DEBUG
      springframework.web: DEBUG
